version: '3'
services:

  transacaobanco:
    image: mysql:latest
    container_name: transacaobanco
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=my-user
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=transacaobanco
